In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
iris=pd.read_csv("/content/Iris_Dataset.csv")
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [48]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [49]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [50]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
label=labelencoder.fit_transform(iris.Species)

In [51]:
iris['Species']=label

In [52]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    int64  
dtypes: float64(4), int64(2)
memory usage: 7.2 KB


In [53]:
x=iris[['Id','SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=iris['Species']

In [54]:
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [55]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [57]:
x_train

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
126  127            6.2           2.8            4.8           1.8
23    24            5.1           3.3            1.7           0.5
64    65            5.6           2.9            3.6           1.3
117  118            7.7           3.8            6.7           2.2
84    85            5.4           3.0            4.5           1.5
..   ...            ...           ...            ...           ...
75    76            6.6           3.0            4.4           1.4
43    44            5.0           3.5            1.6           0.6
22    23            4.6           3.6            1.0           0.2
72    73            6.3           2.5            4.9           1.5
15    16            5.7           4.4            1.5           0.4

[120 rows x 5 columns]

In [58]:
x_test

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
6      7            4.6           3.4            1.4           0.3
3      4            4.6           3.1            1.5           0.2
113  114            5.7           2.5            5.0           2.0
12    13            4.8           3.0            1.4           0.1
24    25            4.8           3.4            1.9           0.2
129  130            7.2           3.0            5.8           1.6
25    26            5.0           3.0            1.6           0.2
108  109            6.7           2.5            5.8           1.8
128  129            6.4           2.8            5.6           2.1
45    46            4.8           3.0            1.4           0.3
48    49            5.3           3.7            1.5           0.2
42    43            4.4           3.2            1.3           0.2
35    36            5.0           3.2            1.2           0.2
5      6            5.4           3.9            1.7           0.4
85    86            6.0           3.4            4.5           1.6
54    55            6.5           2.8            4.6           1.5
41    42            4.5           2.3            1.3           0.3
96    97            5.7           2.9            4.2           1.3
144  145            6.7           3.3            5.7           2.5
89    90            5.5           2.5            4.0           1.3
77    78            6.7           3.0            5.0           1.7
74    75            6.4           2.9            4.3           1.3
115  116            6.4           3.2            5.3           2.3
94    95            5.6           2.7            4.2           1.3
87    88            6.3           2.3            4.4           1.3
29    30            4.7           3.2            1.6           0.2
2      3            4.7           3.2            1.3           0.2
127  128            6.1           3.0            4.9           1.8
44    45            5.1           3.8            1.9           0.4
125  126            7.2           3.2            6.0           1.8

In [59]:
x_test.shape

(30, 5)

In [60]:
x_train.shape

(120, 5)

In [61]:
y_train

126    2
23     0
64     1
117    2
84     1
      ..
75     1
43     0
22     0
72     1
15     0
Name: Species, Length: 120, dtype: int64

In [62]:
y_train.shape

(120,)

In [63]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [64]:
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [65]:
model.predict(x_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2])

In [66]:
model.score(x_test,y_test)

1.0

In [67]:
model.score(x_train,y_train)

1.0

In [68]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)


SVC()

In [69]:
model.predict(x_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2])

In [70]:
model.score(x_test,y_test)

0.9666666666666667

In [71]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [72]:
model.predict(x_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2])

In [73]:
model.predict(x_train)

array([2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1, 0, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 2, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 2,
       1, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 2, 0, 1,
       0, 2, 1, 0, 2, 1, 0, 0, 1, 0])

In [76]:
model.score(x_test,y_test)

1.0

In [78]:
model.score(x_test,y_test)

1.0